version: "3.8"
services:
    localhost_db:        
      image: mariadb:10.3
      ports:
        - 4400:3306
      container_name: localhost_db
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=nera
      volumes:        
        - ./.dev/testing.cnf:/etc/mysql/conf.d/testing.cnf:ro
        - ./.dev/db:/var/lib/mysql              
  
    localhost_phpadmin:
        image: phpmyadmin
        container_name: localhost_phpadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=localhost_db
            - PMA_PORTS=3306
            - PMA_USER=root
            - PMA_PASSWORD=nera
        restart: unless-stopped
        ports:
            - 9001:80
        volumes:
            - ./.dev/data/sessions:/sessions
    
    localhost_app:
      build: ./
      container_name: localhost_app      
      restart: unless-stopped
      ports:
        - 9000:80
      volumes:
        - ./src:/var/www/html:consistent